import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

describe("public assets", () => {
  it("does not ship a stale static index fallback page", async () => {
    await expect(readFile("public/index.html", "utf8")).rejects.toMatchObject({ code: "ENOENT" });
  });

  it("keeps the create-page action out of missing wiki-link styling", async () => {
    const css = await readFile("public/dokuwiki.css", "utf8");
    const missingLinkRule = css.indexOf(".dokuwiki a.wikilink2");
    const createActionRule = css.indexOf(".dokuwiki a.action.create,");

    expect(missingLinkRule).toBeGreaterThanOrEqual(0);
    expect(createActionRule).toBeGreaterThan(missingLinkRule);
    expect(css.slice(createActionRule, createActionRule + 220)).toContain("color: var(--dw-link)");
    expect(css.slice(createActionRule, createActionRule + 220)).toContain(
      ".dokuwiki a.action.create:visited"
    );
  });

  it("keeps DokuWiki media manager frontend hooks available", async () => {
    const js = await readFile("public/dokuwiki.js", "utf8");

    expect(js).toContain("DokuCookie");
    expect(js).toContain("bindHotkeys");
    expect(js).toContain("bindMediaManager");
    expect(js).toContain("bindQuickSearch");
    expect(js).toContain("bindSearchAssistant");
    expect(js).toContain("openLinkWizard");
    expect(js).toContain("openMediaPopup");
    expect(js).toContain("insertTags");
    expect(js).toContain("formatLines");
    expect(js).toContain("autoHeadline");
    expect(js).toContain("pickerToggle");
    expect(js).toContain("bindSectionEditHighlights");
    expect(js).toContain("bindEditorKeyHelpers");
    expect(js).toContain("lockWarningDelay");
    expect(js).toContain("data-media-tree-toggle");
    expect(js).toContain("dokuwiki-media-select");
    expect(js).toContain("#dw__upload[data-media-upload]");
  });

  it("keeps converted upstream CSS module selectors available", async () => {
    const css = await readFile("public/dokuwiki.css", "utf8");
    const selectors = [
      "Generated by scripts/build-dokuwiki-css.mjs",
      "Begin upstream DokuWiki default-template CSS generated from style.ini.",
      "Begin Pages-specific overrides.",
      ".dokuwiki label.block",
      '#dw__login label[for="remember__me"]',
      ".dokuwiki .tabs > ul",
      ".dokuwiki .search-results-form fieldset.search-form",
      ".dokuwiki form.search div.ajax_qsearch",
      "#link__wiz_result",
      "#media__popup_content label",
      "html.popup #mediamgr__aside",
      "html:not(.popup) #mediamgr__aside",
      "#media__content a.mediafile",
      "#mediamanager__page .media-manager__files.filelist",
      "#mediamanager__page .filelist .thumbs li",
      "#mediamanager__diff .imageDiff.opacity .image2",
      ".qq-upload-drop-area",
      ".dokuwiki div.ui-admin ul.admin_tasks",
      ".dokuwiki ul.admin__tools",
      "#dokuwiki__pagetools .create span.icon",
      "#dokuwiki__pagetools .show span.icon",
      "#dokuwiki__pagetools .subscribe span.icon"
    ];

    for (const selector of selectors) {
      expect(css).toContain(selector);
    }

    expect(css).not.toContain("@ini_");
    expect(css).not.toContain("__highlight__");
  });

  it("ships upstream image assets referenced by converted CSS modules", async () => {
    const assets = [
      "public/images/bullet.png",
      "public/images/button-donate.gif",
      "public/images/button-php.gif",
      "public/images/closed-rtl.png",
      "public/images/closed.png",
      "public/images/email.svg",
      "public/images/external-link.svg",
      "public/images/icon-list.png",
      "public/images/icon-sort.png",
      "public/images/license/button/cc-by.png",
      "public/images/license/button/cc-by-nc-sa.png",
      "public/images/license/button/cc-zero.png",
      "public/images/license/button/gnufdl.png",
      "public/images/license/button/publicdomain.png",
      "public/images/license/badge/cc-by.png",
      "public/images/license/badge/cc-by-nc-sa.png",
      "public/images/license/badge/cc-zero.png",
      "public/images/license/badge/gnufdl.png",
      "public/images/license/badge/publicdomain.png",
      "public/images/ns.png",
      "public/images/pagetools/00_default.png",
      "public/images/pagetools/01_edit.png",
      "public/images/pagetools/02_create.png",
      "public/images/pagetools/03_draft.png",
      "public/images/pagetools/04_show.png",
      "public/images/pagetools/05_source.png",
      "public/images/pagetools/06_revert.png",
      "public/images/pagetools/07_revisions.png",
      "public/images/pagetools/08_backlink.png",
      "public/images/pagetools/09_subscribe.png",
      "public/images/pagetools/10_top.png",
      "public/images/pagetools/11_mediamanager.png",
      "public/images/pagetools/12_back.png",
      "public/images/open.png",
      "public/images/page.png",
      "public/images/resizecol.png",
      "public/images/throbber.gif",
      "public/images/unc.svg",
      "public/images/up.png"
    ];

    for (const asset of assets) {
      await expect(readFile(asset)).resolves.toBeInstanceOf(Buffer);
    }
  });

  it("ships upstream editor toolbar icons", async () => {
    const toolbarIcons = [
      "bold.png",
      "chars.png",
      "h.png",
      "h1.png",
      "h2.png",
      "h3.png",
      "h4.png",
      "h5.png",
      "hequal.png",
      "hminus.png",
      "hplus.png",
      "hr.png",
      "image.png",
      "italic.png",
      "link.png",
      "linkextern.png",
      "mono.png",
      "ol.png",
      "sig.png",
      "smiley.png",
      "strike.png",
      "ul.png",
      "underline.png"
    ];

    for (const icon of toolbarIcons) {
      await expect(readFile(`public/images/toolbar/${icon}`)).resolves.toBeInstanceOf(Buffer);
    }
  });
});
