name = "dokutest"
pages_build_output_dir = "public"
compatibility_date = "2026-05-07"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "dokuwiki_pages_dev"
database_id = "bb1c5614-9eb2-4f06-9727-fb41cfb1786b"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "RENDER_CACHE"
id = "ecc7148dc3264d2cb4d9e67283c6fbfd"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "dokuwiki-pages-dev-media"

[[durable_objects.bindings]]
name = "PAGE_LOCKS"
class_name = "PageLockObject"
script_name = "dokutest-page-locks"
