export type DokuWikiConfigCoverageStatus =
  | "implemented"
  | "imported_metadata_only"
  | "intentionally_unsupported"
  | "not_yet_evaluated";

export interface DokuWikiConfigCoverageEntry {
  key: string;
  status: DokuWikiConfigCoverageStatus;
}

export const DOKUWIKI_CONFIG_KEYS = [
  "title",
  "start",
  "lang",
  "template",
  "tagline",
  "sidebar",
  "license",
  "savedir",
  "basedir",
  "baseurl",
  "cookiedir",
  "dmode",
  "fmode",
  "allowdebug",
  "recent",
  "recent_days",
  "breadcrumbs",
  "youarehere",
  "fullpath",
  "typography",
  "dformat",
  "signature",
  "showuseras",
  "toptoclevel",
  "tocminheads",
  "maxtoclevel",
  "maxseclevel",
  "camelcase",
  "deaccent",
  "useheading",
  "sneaky_index",
  "hidepages",
  "useacl",
  "autopasswd",
  "authtype",
  "passcrypt",
  "defaultgroup",
  "superuser",
  "manager",
  "profileconfirm",
  "rememberme",
  "disableactions",
  "auth_security_timeout",
  "securecookie",
  "samesitecookie",
  "remote",
  "remoteuser",
  "remotecors",
  "usewordblock",
  "relnofollow",
  "indexdelay",
  "mailguard",
  "iexssprotect",
  "usedraft",
  "locktime",
  "cachetime",
  "target.wiki",
  "target.interwiki",
  "target.extern",
  "target.media",
  "target.windows",
  "mediarevisions",
  "refcheck",
  "gdlib",
  "im_convert",
  "jpg_quality",
  "fetchsize",
  "subscribers",
  "subscribe_time",
  "notify",
  "registernotify",
  "mailfrom",
  "mailreturnpath",
  "mailprefix",
  "htmlmail",
  "dontlog",
  "logretain",
  "sitemap",
  "rss_type",
  "rss_linkto",
  "rss_content",
  "rss_media",
  "rss_update",
  "rss_show_summary",
  "rss_show_deleted",
  "updatecheck",
  "userewrite",
  "useslash",
  "sepchar",
  "canonical",
  "fnencode",
  "autoplural",
  "compression",
  "gzip_output",
  "compress",
  "cssdatauri",
  "send404",
  "broken_iua",
  "xsendfile",
  "renderer_xhtml",
  "readdircache",
  "search_nslimit",
  "search_fragment",
  "defer_js",
  "hidewarnings",
  "dnslookups",
  "jquerycdn",
  "trustedproxies",
  "realip",
  "proxy.host",
  "proxy.port",
  "proxy.user",
  "proxy.pass",
  "proxy.ssl",
  "proxy.except"
] as const;

const IMPLEMENTED = new Set<string>([
  "title",
  "start",
  "lang",
  "basedir",
  "baseurl",
  "tagline",
  "sidebar",
  "license",
  "recent",
  "recent_days",
  "breadcrumbs",
  "youarehere",
  "fullpath",
  "typography",
  "dformat",
  "signature",
  "showuseras",
  "toptoclevel",
  "tocminheads",
  "maxtoclevel",
  "maxseclevel",
  "camelcase",
  "deaccent",
  "useheading",
  "sneaky_index",
  "hidepages",
  "useacl",
  "autopasswd",
  "superuser",
  "manager",
  "profileconfirm",
  "disableactions",
  "auth_security_timeout",
  "remote",
  "remoteuser",
  "remotecors",
  "usewordblock",
  "relnofollow",
  "iexssprotect",
  "usedraft",
  "locktime",
  "cachetime",
  "target.wiki",
  "target.interwiki",
  "target.extern",
  "target.media",
  "target.windows",
  "mediarevisions",
  "refcheck",
  "fetchsize",
  "notify",
  "registernotify",
  "mailfrom",
  "mailreturnpath",
  "mailprefix",
  "htmlmail",
  "rss_type",
  "rss_linkto",
  "rss_content",
  "rss_media",
  "rss_update",
  "rss_show_summary",
  "rss_show_deleted",
  "sitemap",
  "updatecheck",
  "useslash",
  "sepchar",
  "canonical",
  "fnencode",
  "autoplural",
  "send404",
  "trustedproxies",
  "realip",
  "search_nslimit",
  "search_fragment"
]);

const IMPORTED_METADATA_ONLY = new Set<string>([
  "template",
  "passcrypt",
  "defaultgroup",
  "gdlib",
  "im_convert",
  "jpg_quality"
]);

const INTENTIONALLY_UNSUPPORTED = new Set<string>([
  "savedir",
  "cookiedir",
  "dmode",
  "fmode",
  "allowdebug",
  "authtype",
  "rememberme",
  "indexdelay",
  "subscribers",
  "subscribe_time",
  "dontlog",
  "logretain",
  "userewrite",
  "compression",
  "gzip_output",
  "compress",
  "cssdatauri",
  "broken_iua",
  "xsendfile",
  "renderer_xhtml",
  "readdircache",
  "defer_js",
  "hidewarnings",
  "dnslookups",
  "jquerycdn",
  "proxy.host",
  "proxy.port",
  "proxy.user",
  "proxy.pass",
  "proxy.ssl",
  "proxy.except"
]);

export const DOKUWIKI_CONFIG_COVERAGE: readonly DokuWikiConfigCoverageEntry[] =
  DOKUWIKI_CONFIG_KEYS.map((key) => ({
    key,
    status: coverageStatusForDokuWikiConfigKey(key)
  }));

export function coverageStatusForDokuWikiConfigKey(key: string): DokuWikiConfigCoverageStatus {
  if (IMPLEMENTED.has(key)) return "implemented";
  if (IMPORTED_METADATA_ONLY.has(key)) return "imported_metadata_only";
  if (INTENTIONALLY_UNSUPPORTED.has(key)) return "intentionally_unsupported";
  return "not_yet_evaluated";
}

export function configCoverageCounts(): Record<DokuWikiConfigCoverageStatus, number> {
  return DOKUWIKI_CONFIG_COVERAGE.reduce(
    (counts, entry) => {
      counts[entry.status] += 1;
      return counts;
    },
    {
      implemented: 0,
      imported_metadata_only: 0,
      intentionally_unsupported: 0,
      not_yet_evaluated: 0
    } satisfies Record<DokuWikiConfigCoverageStatus, number>
  );
}
